apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eck-deployer
  annotations:
    github.com/project-slug: fotisolgr/eck-deployer
spec:
  type: other
  lifecycle: unknown
  owner: guests
