
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eck-deployer"
  description: ECK wrapper bash script to deploy Elasticsearch, Filebeat & Kibana to collect logs from all available pods
  annotations:
    backstage.io/kubernetes-id: eck-deployer
    github.com/project-slug: fotisolgr/eck-deployer
  tags:
    - v0.1.0
    - v0.1.1
spec:
  type: service
  owner: user:fotisolgr
  lifecycle: experimental
