
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eck-deployer"
  description: ECK wrapper bash script to deploy Elasticsearch, Filebeat & Kibana to collect logs from all available pods
  annotations:
    backstage.io/kubernetes-id: eck-deployer
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: fotisolgr/eck-deployer
  tags:
    - elastic-search
    - kubernetes
spec:
  type: service
  owner: user:fotisolgr
  system: gemma
  lifecycle: experimental
  dependsOn:
    - component:default/tote
    - resource:default/postgres-db
  providesApis:
    - users-api
  consumesApis:
    - gcloud-api
