apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.2.2 # version will be generated when running `./eck-deployer.sh`
  nodeSets:
    - name: default
      count: 1 # number of Elastic clusters to deploy
      podTemplate:
        metadata:
          labels:
            app: elasticsearch
      config:
        node.store.allow_mmap: false # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html#k8s-virtual-memory
