site_name: ECK Deployer documentation
repo_url: https://github.com/fotisolgr/eck-deployer

nav:
  - Home: home.md
  - About: about.md
  - Contact: contact.md
  - Versions:
      - Latest: index.md
      {% for tag in tags %}
      - {{ tag }}: index.md?tag={{ tag }}
      {% endfor %}

plugins:
  - techdocs-core
  - mkdocs-git-revision-date-localized-plugin:
      type: "localized-date"
#   - search
#   - git-committers:
#       repo_url: https://github.com/fotisolgr/eck-deployer.git
#       tag_order: descending
#       max_tags: 5
#   - git-revision-date-localized:
#       type: tag
  
theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist
