site_name: ECK Deployer documentation
repo_url: https://github.com/fotisolgr/eck-deployer

nav:
  - Intro: 'index.md'
  - Contact: 'contact.md'
  - API:
    - v0.1.0: v0.1.0/mkdocs.yaml
    - v0.1.1: v0.1.1/mkdocs.yaml
    
plugins:
  - techdocs-core
  - monorepo

theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist
